config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root to: 'tasks#index'

  patch 'tasks/:id/done' => 'tasks#mark_as_done', as: 'mark'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy, :update, :mark_as_done]

  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to tasks_path(@task)
    else
      render :new
    end
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def show
  end

  def update
    @task.update(tasks_params)
    if @task.save
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark_as_done
    if @task.done
      @task.done = false
    else
      @task.done = true
    end
    @task.save
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="wrapper-form">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="form-group">
          <%= form_for(task) do |f| %>
            <%= f.label :description %>
            <%= f.text_field :description, placeholder: "my task", class: "form-control" %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render partial: "form", locals: {task: @task} %>

app/views/tasks/index.html.erb
<div class="wrapper padded">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="header marged text-center">
          <h1>My tasks</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 offset-sm-4">
        <div class="wrapper-new padded">
          <%= link_to 'Add a new task', new_task_path %>
        </div>
        <% @tasks.each do |task| %>
            <div class="task-list marged">
              <div>
                <% if task.done %>
                  <%= link_to '', mark_path(task), class: "fa  fa-check-circle fa-2x", method: :patch %>
                <% else %>
                  <%= link_to '', mark_path(task), class: "fa  fa-circle-o fa-2x", method: :patch %>
                <% end %>
              </div>
               <div> <%= link_to task.description, task_path(task) %></div>
                <div class="light-marged-left"><%= link_to '', edit_task_path(task), class: "fa  fa-pencil fa-2x" %>
                  <%= link_to '', task_path(task), class: "fa  fa-trash-o fa-2x", method: :delete, data: { confirm: "Are you sure?" }%></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render partial: "form", locals: {task: @task} %>

app/views/tasks/show.html.erb
<h2>Task detail</h2>
<h1><%= @task.description %></h1>
<p>
  <% if @task.done %>
    <span>done </span>
  <% else %>
    <span>undone </span>
  <% end %>
</p>
<p>Date of creation: <%= @task.created_at %></p>
<p><%= link_to 'Back to index', tasks_path %></p>